import {
  IcoDashboardDark,
  IcoAdminstrationDark,
  IcoBoardDark,
  IcoTeamDark,
  IcoTaskDark,
  IcoDashboardWhite,
  IcoAdminstrationWhite,
  IcoBoardWhite,
  IcoTeamWhite,
  IcoTaskWhite,
  IcoUnicastDark,
  IcoUnicastWhite,
  IcoChecklistDark,
  IcoChecklistWhite,
  IcoTrainingDark,
  IcoTrainingWhite,
  IcoChatDark,
  IcoChatWhite,
  IcoTrackWhite,
  IcoTrackDark,
  IcoAcademyWhite,
  IcoAcademyDark,
} from '../images/icons'

export const navList = [
  {
    link: '/dashboard',
    image: IcoDashboardWhite,
    activeImage: IcoDashboardDark,
    linkName: 'Dashboard',
  },
  {
    link: '/boards',
    image: IcoBoardWhite,
    activeImage: IcoBoardDark,
    linkName: 'Boards',
  },
  {
    link: '/task',
    image: IcoTaskWhite,
    activeImage: IcoTaskDark,
    linkName: 'Task',
  },
  {
    link: '/import-export',
    // activeLink: '/upload/download',
    image: IcoAdminstrationWhite,
    activeImage: IcoAdminstrationDark,
    linkName: 'Export/Import',
    target: '_blank',
  },
  {
    link: '/teamdirectory',
    image: IcoTeamWhite,
    activeImage: IcoTeamDark,
    linkName: 'Team',
  },
  {
    link: '/training',
    image: IcoTrainingWhite,
    activeImage: IcoTrainingDark,
    linkName: 'Manage Training',
    target: '_blank',
  },
  {
    link: '/academy',
    image: IcoAcademyWhite,
    activeImage: IcoAcademyDark,
    linkName: 'Learning Academy',
    target: '_blank',
  },
  {
    link: '/track',
    image: IcoTrackWhite,
    activeImage: IcoTrackDark,
    linkName: 'Track Users',
    target: '_blank',
  },
  {
    link: '/chat',
    image: IcoChatWhite,
    activeImage: IcoChatDark,
    linkName: 'Chat',
    target: '_blank',
  },
  {
    link: '/places',
    image: IcoTrackWhite,
    activeImage: IcoTrackDark,
    linkName: 'Places',
  },
  {
    link: '/schedule',
    image: IcoUnicastWhite,
    activeImage: IcoUnicastDark,
    linkName: 'Engage - Unicasts',
  },
  {
    link: '/checklist',
    image: IcoChecklistWhite,
    activeImage: IcoChecklistDark,
    linkName: 'Checklist',
  },
]
